# Generated by Django 3.2 on 2021-09-08 20:01

import api.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theid', models.CharField(default=api.models.random_with_N_digits_15, editable=False, max_length=15)),
                ('issue_name', models.CharField(max_length=300)),
                ('created_by', models.CharField(max_length=90)),
                ('at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('text', models.CharField(max_length=3000)),
                ('priority', models.CharField(max_length=120)),
                ('assignto', models.CharField(max_length=300)),
                ('isIssueSolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isModerator', models.BooleanField(default=False)),
                ('theUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationID', models.CharField(default=api.models.random_with_N_digits, editable=False, max_length=20)),
                ('toUser', models.CharField(max_length=90)),
                ('thetext', models.CharField(max_length=3000)),
                ('theLink', models.CharField(max_length=3000)),
                ('isSeen', models.BooleanField(default=False)),
                ('IssueReference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issues')),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='project_it_belongs_to',
            field=models.ForeignKey(default=-999, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.projects'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.CharField(default=api.models.random_with_N_digits, editable=False, max_length=20)),
                ('comment', models.CharField(max_length=3000)),
                ('created_by', models.CharField(max_length=90)),
                ('at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('isThisCommentSolution', models.BooleanField(default=False)),
                ('theIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issues')),
            ],
        ),
    ]
