# Generated by Django 3.2 on 2021-04-26 03:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theid', models.CharField(editable=False, max_length=15)),
                ('issue_name', models.CharField(max_length=300)),
                ('created_by', models.CharField(max_length=90)),
                ('at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('text', models.CharField(max_length=3000)),
                ('priority', models.CharField(max_length=120)),
                ('assignto', models.CharField(max_length=300)),
                ('isIssueSolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.CharField(default=polls.models.random_with_N_digits, editable=False, max_length=20)),
                ('comment', models.CharField(max_length=3000)),
                ('created_by', models.CharField(max_length=90)),
                ('at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('isThisCommentSolution', models.BooleanField(default=False)),
                ('theIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.issues')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
