# Generated by Django 3.2 on 2021-04-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_issues_assignto'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='assignto',
            field=models.CharField(default='wd', max_length=300),
            preserve_default=False,
        ),
    ]
