# Generated by Django 3.2 on 2021-04-26 04:11

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_issues_assignto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationID', models.CharField(default=polls.models.random_with_N_digits, editable=False, max_length=20)),
                ('toUser', models.CharField(max_length=90)),
                ('thetext', models.CharField(max_length=3000)),
                ('isSeen', models.BooleanField(default=False)),
            ],
        ),
    ]
