# Generated by Django 3.2 on 2021-04-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='theLink',
            field=models.CharField(default='www.google.com', max_length=3000),
            preserve_default=False,
        ),
    ]
