# Generated by Django 3.2 on 2021-04-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_notifications_thelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='IssueReference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.issues'),
            preserve_default=False,
        ),
    ]
