# Generated by Django 3.2 on 2021-05-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_notifications_issuereference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issues',
            options={'ordering': ['created_by']},
        ),
    ]
