# Generated by Django 3.2 on 2021-05-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_issues_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issues',
            options={},
        ),
    ]
