# Generated by Django 3.2 on 2021-05-29 15:05

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210529_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='project_it_belongs_to',
            field=models.ForeignKey(default=polls.models.default_fkey, on_delete=django.db.models.deletion.CASCADE, to='polls.projects'),
        ),
    ]
