# Generated by Django 3.2 on 2021-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_issues_project_it_belongs_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='theid',
            field=models.CharField(default='NEW', max_length=15),
        ),
    ]
