# Generated by Django 3.2 on 2021-06-13 02:10

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210529_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='theid',
            field=models.CharField(default=polls.models.random_with_N_digits_15, editable=False, max_length=15),
        ),
    ]
