# Generated by Django 3.2 on 2021-06-13 21:30

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_issues_theid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='project_it_belongs_to',
            field=models.ForeignKey(default=polls.models.default_fkey, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='polls.projects'),
        ),
    ]
