# Generated by Django 3.2 on 2021-04-21 16:21

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='theid',
            field=models.CharField(default=registration.models.createID, max_length=15),
        ),
    ]
