# Generated by Django 3.2 on 2021-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_profile_theuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isModerator',
            field=models.BooleanField(default=False),
        ),
    ]
