# Generated by Django 3.2 on 2021-09-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_profile_ismoderator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
